const loginFields = [
  {
    labelText: "Email ",
    labelFor: "email-address",
    id: "email-address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];
const forgetPasswordFields = [
  {
    labelText: "Email",
    labelFor: "email-address",
    id: "email-address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
];
const signupFields = [
  {
    labelText: "Full Name",
    labelFor: "fullname",
    id: "fullname",
    name: "fullname",
    type: "text",
    autoComplete: "fullname",
    isRequired: true,
    placeholder: "Black Samuel",
  },
  {
    labelText: "Email",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "blacksamuel@gmail.com",
  },
  {
    labelText: "Phone Number",
    labelFor: "phone_number",
    id: "phone_number",
    name: "phone_number",
    type: "tel",
    autoComplete: "phone_number",
    isRequired: true,
    placeholder: "09010000000",
  },
  {
    labelText: "Address",
    labelFor: "address",
    id: "address",
    name: "address",
    type: "text",
    autoComplete: "address",
    isRequired: true,
    placeholder: "43 random avenue CBS Great",
  },
  {
    labelText: "City",
    labelFor: "city",
    id: "city",
    name: "city",
    type: "text",
    autoComplete: "city",
    isRequired: true,
    placeholder: "Abuja",
  },
  {
    labelText: "State",
    labelFor: "state",
    id: "state",
    name: "state",
    type: "text",
    autoComplete: "state",
    isRequired: true,
    placeholder: "Fedral Capital Teritory",
  },
  {
    labelText: "Date of birth",
    labelFor: "date_of_birth",
    id: "date_of_birth",
    name: "date_of_birth",
    type: "text",
    autoComplete: "date_of_birth",
    isRequired: true,
    placeholder: "2023-03-25",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "*******",
  },
  {
    labelText: "Confirm Password",
    labelFor: "password_confirmation",
    id: "password_confirmation",
    name: "password_confirmation",
    type: "password",
    autoComplete: "password_confirmation",
    isRequired: true,
    placeholder: "*******",
  },
];

const resetPasswordFields = [
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "********",
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirm-password",
    id: "confirm-password",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "********",
  },
];

export { loginFields, signupFields, forgetPasswordFields, resetPasswordFields };
